version: '3'
services:
  web:
    working_dir: /var/app
    env_file:
      - variables.env
    ports:
     - '8080:80'    
    # entrypoint: 'sh /docker-entrypoint.sh npm run start'
    build:
      context: ./
